### PR TITLE
Fix verbose messages in Set-ePOTag

### PR DESCRIPTION
**Pull request by hjbotha**

### CODE REVIEW

**Comment by marranaga** [comment]
@hjbotha, while there are some additions that I do like (like fixing my oversight with the `Write-Verbose` messages, and thanks for catching that!), there are some parts that I don't feel provide much to the code.

I like [this](https://github.com/UNT-CAS/ePOwerShell/pull/28/files/368a4031b58312fe57af62f05ebdce1d46cfdd4c..f0910b9629aa741d6bc898dd6d98b9c61bae6e70#diff-8e48db19b3586edc9cc6079943920bb6R42-R44) idea, however I think we should be checking via the `IsNullOrEmpty` method in the string class. Thoughts?

As for the rest, I think we're already on the same page. In the [Add-TagID-To-Set/Remove-ePOTag](https://github.com/UNT-CAS/ePOwerShell/tree/Add-TagID-To-Set/Remove-ePOTag) branch, there was a [commit](https://github.com/UNT-CAS/ePOwerShell/commit/f41d2cff54b9e45b131edf5e9f3e545f5ab36037) on Friday with a lot of similar code. The main reason that's not merged yet is because I want to update the effected Pester tests so that I can get a higher code coverage (currently sitting in the mid 70's 🤦‍♂).

**Comment by hjbotha** [comment]
Ah oops, I didn't mean to include the last commit in this pull request - just the fixes to the messaging. Not experienced with pull requests sorry. The rest of it was just a little mental POCing for a current project. Thanks for your work!

**Comment by hjbotha** [comment]
Much prefer your approach of always doing it by id, and finding the ID if these cmdlets are not passed ePOComputer objects anyway. :)

**Comment by marranaga** [comment]
@hjbotha, I won't be accepting this PR. If you'd like, please read our short [Contribution](https://github.com/UNT-CAS/ePOwerShell/wiki/Contribution) page in the Wiki, and feel free to submit a new PR! Thank you again.

**Pull request closed without merging**
